# Generated by Django 2.1.2 on 2019-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginplace', models.CharField(max_length=40)),
                ('descinationplace', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=40)),
            ],
        ),
    ]
