# Generated by Django 2.1.2 on 2019-03-22 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
