# Generated by Django 2.1.2 on 2019-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_fly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='descinationplace',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fly',
            name='orginplace',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
