# Generated by Django 2.1.2 on 2019-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0003_auto_20190322_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='orginplace',
            field=models.CharField(blank=True, default='Warsaw', max_length=40),
        ),
    ]
