# Generated by Django 2.1.2 on 2019-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_auto_20190322_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD')], max_length=40),
        ),
    ]
