# Generated by Django 2.1.2 on 2019-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0005_auto_20190322_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
