# Generated by Django 2.1.2 on 2019-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0006_auto_20190322_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='minFlight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
