# Generated by Django 2.1.2 on 2019-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0007_fly_minflight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='day',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fly',
            name='month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fly',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
