# Generated by Django 2.1.2 on 2019-03-22 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0008_auto_20190322_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
