# Generated by Django 2.1.2 on 2019-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0009_auto_20190322_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
