# Generated by Django 2.1.2 on 2019-03-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0010_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='airports',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fly.Country'),
        ),
    ]
