# Generated by Django 2.1.2 on 2019-03-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0011_fly_airports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='airports',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='fly.Country'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
