# Generated by Django 2.1.2 on 2019-03-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0014_auto_20190322_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fly',
            old_name='minFlight',
            new_name='number_city',
        ),
    ]
