# Generated by Django 2.1.2 on 2019-03-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0015_auto_20190322_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='country',
            name='name3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='country',
            name='name4',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
