# Generated by Django 2.1.2 on 2019-03-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0016_auto_20190326_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
