# Generated by Django 2.1.2 on 2019-03-28 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0017_country_country_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='number_city',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fly',
            name='orginplace',
            field=models.CharField(blank=True, default='Warsaw', help_text='Start place', max_length=40),
        ),
    ]
