# Generated by Django 2.1.2 on 2019-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0018_auto_20190329_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
