# Generated by Django 2.1.2 on 2019-03-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0019_auto_20190329_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='airports',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.Country'),
        ),
    ]
