# Generated by Django 2.1.2 on 2019-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0020_auto_20190329_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
