# Generated by Django 2.1.2 on 2019-04-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0022_auto_20190330_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='descinationplace',
            field=models.CharField(blank=True, default=0, max_length=40),
            preserve_default=False,
        ),
    ]
